a에 값 1을 넣고, a의 type을 print함. a의 type은 int로 표기(integer의 약자)

In [1]:
a = 1; print(type(a))

<class 'int'>


float(a)는 a를 소수점이 있는 숫자로 변환하는 함수. print도 타입 float가 됨.

In [3]:
a = 1; a = float(a); print(type(a))

<class 'float'>


int(a)는 a를 정수로 변환하는 함수. print도 타입 int가 됨.

In [2]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


''는 숫자가 아닌 문자열 타입이며 str으로 표기(string의 약자), [1]은 두번째 문자열인 2를 의미(문자열 순서는 0부터 시작)

In [4]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


list는 자료열을 의미함. a[2]는 3번째 순서를 의미.

In [5]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


list안에 또다른 list를 구성할 수 있음을 보여줌.

In [6]:

a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


tuple : 소괄호로 묶여있는 자료열을 의미.

In [7]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])


<class 'tuple'>
1
2
[3, '4']


중괄호로 묶여있는 dictionary. key와 각 key에 해당하는 value가 존재. print(a[a])는 a라는 dic안에 a라는 key의 value를 프린트하라는 의미이고 여기서는 apple임.

In [8]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


list 자료열의 자료값으로 tuple을 넣어봄.

In [9]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

array는 matrix 비슷한 형태. numpy.ndarray: numpy 폴더의 n dimension array임.

In [11]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


array를 통한 수식 계산.

In [12]:
print(b*b)


[[ 1  4  9]
 [ 9 64  0]]


np.matrix(b)라는 함수를 이용하여 array형태의 b를 matrix로 변환.

In [13]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


c는 (2,3)형태의 matrix임. 두 행렬의 열과 행이 동일하지 않기 때문에 c* c는 수식 불가.

In [14]:
c*c


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

c.T는 c를 transpose 해 줌. 결과는 (2,2)형태의 matrix.

In [15]:
c*c.T


matrix([[14, 19],
        [19, 73]])